### ISSUE TITLE
مشکل در بیلد ایمیج داکر

### ISSUE THREAD

**Issue by CoAGULA-GOAT** [parmenides/hotspotplus#2]
سلام من میخواستم چندتا از پوشه ها رو دوباره بیلد کنم ولی بیلد میشه ایمج رو ران میکنم npm خطا داره و درست کار نمیکنه کسی میتونه به حلش کمک کنه

`

### **لاگ بیلد ام هستش**

` ---> Running in 830f6c6a0164
Removing intermediate container 830f6c6a0164
 ---> 8ceeca86a1c3
Step 4/11 : RUN mkdir /key
 ---> Running in b6a2608c42f3
Removing intermediate container b6a2608c42f3
 ---> b08cb2fe020d
Step 5/11 : COPY . /app
 ---> eb322e2316f1
Step 6/11 : WORKDIR /app
 ---> Running in 680b7f80b8fa
Removing intermediate container 680b7f80b8fa
 ---> 1da8352db2f8
Step 7/11 : ENV NPM_CONFIG_PREFIX=/app/.npm-global
 ---> Running in 1c4081eb7894
Removing intermediate container 1c4081eb7894
 ---> 7bef5ba6f2c3
Step 8/11 : ENV PATH=$PATH:/app/.npm-global/bin
 ---> Running in 648ec0ad317d
Removing intermediate container 648ec0ad317d
 ---> 62af51ff0654
Step 9/11 : RUN npm i npm@latest -g
 ---> Running in c4fb87319f75
/app/.npm-global/bin/npm -> /app/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/app/.npm-global/bin/npx -> /app/.npm-global/lib/node_modules/npm/bin/npx-cli.js
npm WARN notsup Unsupported engine for npm@8.3.2: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: npm@8.3.2
npm@8.3.2
added 214 packages from 96 contributors in 8.762s
Removing intermediate container c4fb87319f75
 ---> 21192d4926b6
Step 10/11 : RUN npm install --only=production
 ---> Running in 2cf4e938c36d
npm WARN deprecated nsp@2.8.1: The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting
npm WARN deprecated jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates
npm WARN deprecated loopback-boot@2.28.0: This version is no longer supported, please upgrade to 3.x
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated wreck@6.3.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated loopback-component-explorer@4.3.1: This version is no longer supported, please upgrade to 6.x
npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>. Thanks to @shadowgate15, @spence-s, and @niftylettuce. Superagent is sponsored by Forward Email at <https://forwardemail.net>.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

-> dtrace-provider@0.8.8 install /app/node_modules/dtrace-provider
-> node-gyp rebuild || node suppress-error.js

make: Entering directory '/app/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/app/node_modules/dtrace-provider/build'

-> core-js-pure@3.20.3 postinstall /app/node_modules/core-js-pure
-> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
-> https://opencollective.com/core-js 
-> https://patreon.com/zloirock 
-> https://paypal.me/zloirock 
-> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

-> ejs@2.7.4 postinstall /app/node_modules/ejs
-> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for formdata-node@4.3.2: wanted: {"node":">= 12.20"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: formdata-node@4.3.2
npm WARN notsup Unsupported engine for web-streams-polyfill@4.0.0-beta.1: wanted: {"node":">= 12"} (current: {"node":"10.24.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: web-streams-polyfill@4.0.0-beta.1

added 580 packages from 490 contributors and audited 736 packages in 67.92s

21 packages are looking for funding
  run `npm fund` for details

found 31 vulnerabilities (3 low, 19 moderate, 6 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 2cf4e938c36d
 ---> 1095bfc460d9
Step 11/11 : CMD npm start
 ---> Running in 6b8c3deeb0c4
Removing intermediate container 6b8c3deeb0c4
 ---> 73b5a3c53796
Successfully built 73b5a3c53796
Successfully tagged apilicense:latest`

### **این اروریه که موقع ران بهش بر میخورم**

-> license-api@1.0.0 start /app
-> node server/server.js

internal/url.js:243
  throw error;
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: http://undefined:undefined
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at getUsernameAndPassword (/app/node_modules/@elastic/elasticsearch/index.js:248:38)
    at getAuth (/app/node_modules/@elastic/elasticsearch/index.js:239:16)
    at new Client (/app/node_modules/@elastic/elasticsearch/index.js:70:23)
    at Object.<anonymous> (/app/server/modules/aggregates.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/common/models/license.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at requireNodeOrEsModule (/app/node_modules/loopback-boot/lib/require.js:7:17)
    at /app/node_modules/loopback-boot/lib/executor.js:248:20
    at Array.forEach (<anonymous>)
    at defineModels (/app/node_modules/loopback-boot/lib/executor.js:229:23)
    at setupModels (/app/node_modules/loopback-boot/lib/executor.js:197:3)
    at execute (/app/node_modules/loopback-boot/lib/executor.js:40:3)
    at bootLoopBackApp (/app/node_modules/loopback-boot/index.js:154:3)
    at Object.<anonymous> (/app/server/server.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! license-api@1.0.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the license-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-23T14_57_39_217Z-debug.log

**Comment by pysf** [comment]
این کامند رو از کجا آوردید؟
مسیر ./api-license/ مدتهاست که حذف شده
برنامه نیازی به لایسنس نداره

**Comment by pysf** [comment]
کدوم پروژه رو میخواهید بیلد کنید؟

**Comment by CoAGULA-GOAT** [comment]
> کدوم پروژه رو میخواهید بیلد کنید؟

api-license

**Comment by pysf** [comment]
این فولدر وجود نداره تو گیت هات اسپات پلاس، حذف شده. فکر کنم روی نسخه قدیمی دارید کار میکنید.

**Comment by CoAGULA-GOAT** [comment]
bale 7.0.33
